apiVersion: apps/v1    
kind: Deployment       
metadata:
  labels:
    app: simple-webhook-deploy
  name: simple-webhook-deploy
  namespace: simple-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webhook-deploy
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-webhook-deploy
    spec:
      volumes:
      - name: nginx-certs
        secret:
          secretName: webhook-tls
      - name: nginx-conf
        configMap:
          name: webhook-proxy-cm
      containers:
      - image: nginx:alpine
        name: proxy
        volumeMounts:
          - mountPath: /etc/nginx
            name: nginx-conf
          - mountPath: /etc/pki/
            name: nginx-certs
            readOnly: true
      - image: kerolosayman308/golang:simple-admission-webhook-1.0
        name: golang
        resources: 
          requests:
            memory: 50Mi
            cpu: "0.5"