apiVersion: v1
kind: Service
metadata:
  name: simple-webhook-svc
  namespace: simple-webhook
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: https
    port: 8000
    targetPort: 8000
  selector:
    app: simple-webhook-deploy